// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_service.proto

// Protobuf Java Version: 3.25.2
package rs.raf.pds.faulttolerance.gRPC;

public interface LogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 laskKnownIndex = 1;</code>
   * @return The laskKnownIndex.
   */
  long getLaskKnownIndex();
}
